-- ========================================
-- 修复 admins 表缺少 password 列的问题
-- 错误: column "password" of relation "admins" does not exist
-- ========================================

-- 1. 添加 password 列（如果不存在）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'admins' AND column_name = 'password'
  ) THEN
    ALTER TABLE admins ADD COLUMN password TEXT;
    RAISE NOTICE '✅ 已添加 password 列到 admins 表';
  ELSE
    RAISE NOTICE '⚠️ password 列已存在，跳过添加';
  END IF;
END;
$$;

-- 2. 为现有管理员设置默认密码（bcrypt 哈希：admin123）
-- bcrypt hash of 'admin123' (cost 10, generated by crypt('admin123', gen_salt('bf')))
UPDATE admins
SET password = crypt('admin123', gen_salt('bf'))
WHERE password IS NULL;

RAISE NOTICE '✅ 已为 % 个管理员设置默认密码 (admin123)', (SELECT COUNT(*) FROM admins WHERE password IS NOT NULL);

-- 3. 验证结果
DO $$
DECLARE
  total_admins INTEGER;
  with_password INTEGER;
BEGIN
  SELECT COUNT(*) INTO total_admins FROM admins;
  SELECT COUNT(*) INTO with_password FROM admins WHERE password IS NOT NULL;
  
  RAISE NOTICE '📊 管理员总数: %', total_admins;
  RAISE NOTICE '📊 有密码的管理员: %', with_password;
  
  IF total_admins = with_password THEN
    RAISE NOTICE '✅ 所有管理员都有密码';
  ELSE
    RAISE WARNING '⚠️ 还有 % 个管理员没有密码', total_admins - with_password;
  END IF;
END;
$$;

-- 4. 修改 rpc_login 函数（使用 password 列验证）
-- 先删除旧函数
DROP FUNCTION IF EXISTS rpc_login(TEXT, TEXT);
DROP FUNCTION IF EXISTS rpc_login(p_username TEXT, p_password TEXT);

CREATE OR REPLACE FUNCTION rpc_login(
  p_username TEXT,
  p_password TEXT
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  admin_record admins%ROWTYPE;
BEGIN
  -- 查找管理员（验证密码）
  SELECT * INTO admin_record
  FROM admins
  WHERE username = p_username
    AND password = crypt(p_password, password);

  IF NOT FOUND THEN
    RETURN jsonb_build_object('error', '用户名或密码错误');
  END IF;

  -- 返回管理员信息（不包含密码）
  RETURN jsonb_build_object(
    'data', jsonb_build_object(
      'id', admin_record.id,
      'username', admin_record.username,
      'name', admin_record.name,
      'phone', admin_record.phone,
      'role', admin_record.role,
      'store_id', admin_record.store_id
    )
  );
END;
$$;

RAISE NOTICE '✅ rpc_login 函数已更新（使用 password 列）';

-- 完成提示
DO $$
BEGIN
  RAISE NOTICE '✅ ========================================';
  RAISE NOTICE '✅ admins 表 password 列修复完成';
  RAISE NOTICE '✅ 现有管理员默认密码: admin123';
  RAISE NOTICE '✅ 请在前端测试登录功能';
  RAISE NOTICE '✅ ========================================';
END;
$$;
